# Generated by Django 4.2.3 on 2023-07-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
    ]
