# Generated by Django 4.2.3 on 2023-08-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['identification'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
    ]
