# Generated by Django 4.2.3 on 2023-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
    ]
