# Generated by Django 4.2.3 on 2023-08-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0002_alter_doctor_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='cedula',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='especialidad',
            new_name='specialty',
        ),
    ]
