# Generated by Django 4.2.3 on 2023-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo_estancia',
                'verbose_name_plural': 'Tipo_estancias',
            },
        ),
        migrations.CreateModel(
            name='Uci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
                ('capacidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Uci',
                'verbose_name_plural': 'Ucis',
            },
        ),
        migrations.CreateModel(
            name='Ucim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=200)),
                ('capacidad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ucim',
                'verbose_name_plural': 'Ucims',
            },
        ),
    ]
