# Generated by Django 4.2.3 on 2023-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stay Type',
                'verbose_name_plural': 'Stay Types',
                'ordering': ['name'],
            },
        ),
    ]
