# Generated by Django 4.2.3 on 2023-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0002_rename_tipo_estancia_tipoestancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestancia',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
