# Generated by Django 4.2.3 on 2023-08-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('who_created', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('identification', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_born', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['identification'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('date_departure', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('muerto', 'Muerto'), ('vivo', 'Vivo'), ('en revision', 'En revision')], max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.patient')),
                ('stay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.staytype')),
            ],
            options={
                'verbose_name': 'Medical Historial',
                'verbose_name_plural': 'Medical Historials',
                'ordering': ['patient'],
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('doctor_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.patient')),
            ],
            options={
                'verbose_name': 'Medical Data',
                'verbose_name_plural': 'Medical Data',
                'ordering': ['patient'],
            },
        ),
    ]
