# Generated by Django 4.2.3 on 2023-07-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_actualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='quien_creo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
