# Generated by Django 4.2.3 on 2023-08-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_comorbidity_alter_medicalhistory_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='comorbidity',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.patient'),
        ),
    ]
