# Generated by Django 4.2.3 on 2023-08-21 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0001_initial'),
        ('pacientes', '0003_comorbidity_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nationality',
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationality.country'),
        ),
    ]
