# Generated by Django 4.2.3 on 2023-07-14 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(max_length=200)),
                ('doctor_a_cargo', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
