# Generated by Django 4.2.3 on 2023-07-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_cama_uci_ucim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cama',
        ),
        migrations.DeleteModel(
            name='Uci',
        ),
        migrations.DeleteModel(
            name='Ucim',
        ),
    ]
