# Generated by Django 4.2.3 on 2023-07-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
        ('pacientes', '0006_delete_cama_delete_uci_delete_ucim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='datosmedicos',
            name='doctor_a_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.estancia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
