# Generated by Django 4.2.3 on 2023-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_estancia_alter_datosmedicos_doctor_a_cargo_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
