# Generated by Django 4.2.3 on 2023-07-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0004_delete_cama_delete_uci_delete_ucim'),
        ('pacientes', '0008_historial_fecha_ingreso_historial_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='estancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.tipoestancia'),
        ),
        migrations.DeleteModel(
            name='Estancia',
        ),
    ]
