# Generated by Django 4.2.3 on 2023-07-17 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_rename_estancia_historial_tipo_estancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
