# Generated by Django 4.2.3 on 2023-07-17 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_alter_historial_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
