# Generated by Django 4.2.3 on 2023-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_alter_historial_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
