# Generated by Django 4.2.3 on 2023-07-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_alter_historial_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='condicion',
            field=models.CharField(blank=True, choices=[('muerto', 'Muerto'), ('vivo', 'Vivo'), ('en revision', 'En revision')], max_length=20, null=True),
        ),
    ]
